### PR TITLE
Fix the link URL in 2013-11-11-TimeLines.md

### PR DESCRIPTION
**Pull request by vflyson**
The game's page is gone from the steam store for some reason.
Fixed it by replacing the URL with a link to an article on wikipedia.

### CODE REVIEW

**Comment by elmindreda** [comment]
Thank you for reporting this.

The whole media page should be redone. It's my fault it hasn't happened yet. Will fix.

**Comment by vflyson** [comment]
Could you please merge this one in or close the PR in case you feel like this is unnecessary?
Thanks.

**Comment by elmindreda** [comment]
I apologize for my Barliman-esque memory. I've disabled the media page for now. The proper solution is #32.

**Comment by vflyson** [comment]
It's all good. I'll close this PR then, hope to see the new media page up soon!

**Pull request closed without merging**
