### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

*Total: 3.51kb -> 3.24kb (7.75%)

\img\monitors.png -- 1.45kb -> 1.34kb (7.99%)
\img\clock.png -- 2.06kb -> 1.90kb (7.59%)

### CODE REVIEW

**Comment by elmindreda** [comment]
Hello bot. Will review.

**Comment by siavashserver** [comment]
This is nice :-)

*pets ImgBot*

**Comment by elmindreda** [comment]
@siavashserver It's great!

@ImgBotApp Thank you!

**Comment by dabutvin** [comment]
👍 happy to help

If you want more prs from ImgBot here, or any of your other projects, feel free to install the GitHub app.

https://github.com/apps/ImgBot

**Pull request merged**
