### PR TITLE
Mobile fixes and basic SEO

### PR DESCRIPTION
**Pull request by siavashserver**
Hello, here is couple a of changes I made to improve the website performance on mobile devices, and hopefully make it more search engine friendly 🔥🔥🔥

**Important note:**
Please make sure that `JEKYLL_ENV=production` environment variable has been set before running production builds, otherwise `jekyll-seo-tag` and `jekyll-minifier` plugins will fail to perform their magic correctly.

**Better responsive design on small screens and mobile devices:**
- Updated PureCSS to v2.0.3.
- Merged PureCSS components with our CSS to reduce resource requests.
- Merged default and frontpage Jekyll layouts.
- Splitted the milestone component script on home page.
- Removed buttons.rb and grids.rb Jekyll plugins; Jekyll is able to process
  markdown inside raw HTML tags since one of 3.x minor releases.

**Common search engine optimizations:**
- Added `jekyll-seo-tag` plugin to automate SEO process.
- Added basic `description` attribute to all pages.
- Added a bunch of *favicons*.
- Improved touch area of page footer links for mobile users.
- Preconnect to the GitHub API to improve home page load times.
- Added `jekyll-minifier` plugin to automate output minification process.

Addresses #70 .

### CODE REVIEW

**Comment by elmindreda** [comment]
Thank you! Modulo the minifier this also should bring us several steps closer to being able to build on GitHub Pages.

I noticed that with these changes the lead text can get very close to the buttons for some widths


Also the example code in documentation.md is now very narrow on mobile, seemingly because we lost `figure{margin:0}`

**Comment by siavashserver** [comment]
Nice catch, should be fixed now. 👍

**Comment by siavashserver** [comment]
I think it should be ready now.

**Comment by elmindreda** [comment]
Thank you so much!

**Comment by siavashserver** [comment]
You are welcome 😊

**Pull request merged**
